### ISSUE TITLE
Fields Keep Spinning

### ISSUE THREAD

**Issue by Dovydassilver** [zjut-bio-party-undergraduate-branch/Excel-Compare-and-Import#477]
Hi, I found this extension super useful, there's no other alternative on Lark and I want to report a bug that prevents me to use it. Sometimes I get the field section keep spinning, and it spins forever, even after I reset the plugin, unpin and pin again, turn off lark as come back tomorrow - still spins:
<img width="535" alt="image" src="https://github.com/user-attachments/assets/10be136d-c01d-4972-a7ae-d3e228ebe04f">

[Excel_Compare_and_Import_Log_1722978322517.json](https://github.com/user-attachments/files/16515713/Excel_Compare_and_Import_Log_1722978322517.json)

Attaching log if that helps. 

Please understand that this extension is extremely important for our business flow. @497363983

**Comment by 497363983** [comment]
@Dovydassilver Hello, I guess the reason for this is that there are link fields (single or duplex) in this table. However, the logged-in user does not have the permission to access the table associated with this field, so the extension cannot obtain the meta information of the linked table. In order to ensure that the values of the link fields can be written correctly, the extension needs to obtain the information about the linked tables, and at least the read permission is required.

**Comment by 497363983** [comment]
I think the extension needs a better way to handle it here, and maybe it would be a better choice to filter out the link fields that can't get the linked table

**Comment by 497363983** [comment]
@Dovydassilver New version is released, you can try it.
